
name: Run Backend Tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: install
          working-directory: ./backend
          run: npm install
        - name: create env file
          run: |
            touch .env
            echo DB_URL=${{ secrets.ENGINE_API_KEY }} >> .env
        - name: backend tests
          working-directory: ./backend
          run: npm test
